const jsonData = [
  { id: 1, category: 'Assault Rifle', name: 'XM4', url: '../img/xm4.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 2, category: 'Assault Rifle', name: 'AK-74', url: '/img/ak-74.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 3, category: 'Assault Rifle', name: 'AMES 85', url: '/img/ames 85.webp', headshots: 100, special_1: true, special_2: true, gold: true },
  { id: 4, category: 'Assault Rifle', name: 'GPR 91', url: '/img/gpr 91.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 5, category: 'Assault Rifle', name: 'Model L', url: '/img/model l.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 6, category: 'Assault Rifle', name: 'Goblin Mk2', url: '/img/goblin mk2.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 7, category: 'Assault Rifle', name: 'AS VAL', url: 'file:///D:/WebDev/Grant/cod-weapons/img/as val.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 8, category: 'Launcher', name: 'CIGMA 2B', url: '/img/cigma 2b.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 9, category: 'Launcher', name: 'HE-1', url: '/img/he-1.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 10, category: 'LMG', name: 'PU-21', url: '/img/pu-21.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 11, category: 'LMG', name: 'XMG', url: '/img/xmg.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 12, category: 'LMG', name: 'GPMG-7', url: '/img/gpmg-7.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 13, category: 'Marksman Rifle', name: 'SWAT 5.56', url: '/img/swat 5.56.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 14, category: 'Marksman Rifle', name: 'Tsarkov 7.62', url: '/img/tsarkov 7.62.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 15, category: 'Marksman Rifle', name: 'AEK-973', url: '/img/aek-973.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 16, category: 'Marksman Rifle', name: 'DM-10', url: '/img/dm-10.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 17, category: 'Melee', name: 'Knife', url: '/img/knife.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 18, category: 'Melee', name: 'Baseball Bat', url: '/img/baseball bat.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 19, category: 'Pistol', name: 'GS45', url: '/img/gs45.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 20, category: 'Pistol', name: '9MM PM', url: '/img/9mm pm.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 21, category: 'Pistol', name: 'Grekhova', url: '/img/grekhova.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 22, category: 'Pistol', name: 'Stryder .22', url: '/img/stryder 22.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 23, category: 'Shotgun', name: 'Marine SP', url: '/img/marine sp.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 24, category: 'Shotgun', name: 'ASG-89', url: '/img/asg-89.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 25, category: 'SMG', name: 'C9', url: '/img/c9.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 26, category: 'SMG', name: 'KSV', url: '/img/ksv.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 27, category: 'SMG', name: 'Tanto .22', url: '/img/tanto .22.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 28, category: 'SMG', name: 'Jackal PDW', url: '/img/jackal pdw.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 29, category: 'SMG', name: 'Kompakt 92', url: '/img/kompakt 92.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 30, category: 'Sniper', name: 'LW3A1 Frostline', url: '/img/lw3a1 frostline.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 31, category: 'Sniper', name: 'SVD', url: '/img/svd.webp', headshots: 0, special_1: false, special_2: false, gold: false },
  { id: 32, category: 'Sniper', name: 'LR 7.62', url: '/img/lr 7.62.webp', headshots: 0, special_1: false, special_2: false, gold: false },
];
